### PR TITLE
Fix remaining bugs in PE-D

### LINKED ISSUE #207: [PE-D][Tester E] Instructions unclear after cancelling delete
Was unsure how to go back to normal after cancelling delete,

it went back to normal after command list, would help if instructions were given in the output panel, or auto list

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: zechary28/ped#3

### PR DESCRIPTION
**Pull request by yuqiannemo**
Fixes #207 #199 #213

### CODE REVIEW

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -64,8 +64,8 @@ public CommandResult execute(String commandText) throws CommandException, ParseE
                 }
             } else {
                 String cancelMessage = pendingCommand instanceof DeleteCommand
-                        ? "Deletion cancelled."
-                        : "Update cancelled.";
+                        ? "Deletion cancelled. Type 'list' to see the list of applicants."
+                        : "Update cancelled. Type 'list' to see the list of applicants.";
```
Comment (wswddl) [inline src/main/java/seedu/address/logic/LogicManager.java:68]: LGTM

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -95,9 +95,29 @@ private static void checkLength(String fieldName, String value) throws ParseExce
...
+                } else if (prefix.equals(PREFIX_JOB_POSITION)) {
+                    ParserUtil.parseJobPosition(value);
+                } else if (prefix.equals(PREFIX_STATUS)) {
+                    ParserUtil.parseStatus(value);
+                }
+            }
+        }
+
+        // If all validations passed, create the predicates
         PREFIX_MAPPING.forEach((prefix, predicateConstructor) ->
```
Comment (wswddl) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:117]: Remove whitespace so checkstyle won't complain and also reduce LoC change.

**Review by wswddl — COMMENTED** [review]
Some minor issues

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 2 above)
Comment (yuqiannemo) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:117]: OK I have removed the blank lines
