### PR TITLE
Fix clear command doesn't remove all the applicant photos in the data file

### LINKED ISSUE #153: Bug: Profile pic window can be opened multiple times.
When I double or triple click the profile, I can open up several windows to update the profile pic at once. I don't think this is the expected behaviour. Users should only be able to open up one window at a time, if not it gets confusing. I would recommend using a double click to open the profile picture instead, to prevent accidental opening

### LINKED ISSUE #155: Bug: `clear` command doesn't remove all the applicant photos in the data file

### LINKED ISSUE #156: Bug: Oversize image files causes huge lag to the application
Possible solution: limit the image file size.

### PR DESCRIPTION
**Pull request by wswddl**
- Fix clear command doesn't remove all the applicant photos in the data file. Fixes #155 
- Image file size is too big which causes lags. Fixes #156 
- Only allow one pop up window at any given time. Fixes #153

### CODE REVIEW

**Comment by wswddl** [comment]
fix #155

**Review by ernestlsy — APPROVED** [review]
LGTM, elegant solutions!

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -11,7 +11,6 @@
 import java.util.stream.Collectors;
 
 import javafx.collections.ObservableList;
-import javafx.stage.FileChooser;
```
Comment (GabriellaGloria) [inline src/main/java/seedu/address/logic/LogicManager.java:14]: Thanks for removing the unused imports!

File: src/main/java/seedu/address/model/applicant/Applicant.java [hunk 2]
```diff
@@ -158,13 +158,15 @@ public boolean isSamePerson(Applicant otherApplicant) {
     }
 
     /**
-     * Delete the image file in the profile pictures folder if it is not the default profile picture.
+     * Deletes the image file in the profile pictures folder if it is not the default profile picture.
```
Comment (GabriellaGloria) [inline src/main/java/seedu/address/model/applicant/Applicant.java:161]: Great catch!

**Review by GabriellaGloria — APPROVED** [review]
Looks great, Approved!

**Review by yuqiannemo — COMMENTED** [review]
LGTM!

**Comment by yuqiannemo** [comment]
Please resolve the merge conflict @wswddl

**Comment by yuqiannemo** [comment]
> Please resolve the merge conflict @wswddl

I solved it just now

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 3]
```diff
@@ -242,14 +252,33 @@ private File chooseProfilePicture() {
...
+        isProfilePicClicked = false;
+
+        // check if the chosen file is too big
+        if (selectedFile != null && selectedFile.length() > MAX_FILE_SIZE) {
+            // Alert the user if the file is too large
+            Alert alert = new Alert(Alert.AlertType.ERROR);
+            alert.setTitle("File Too Large");
+            alert.setHeaderText("The selected file is too large.");
+            alert.setContentText("Please select a file smaller than 2MB.");
+            alert.showAndWait();
```
Comment (yuqiannemo) [inline src/main/java/seedu/address/ui/PersonCard.java:275]: Might be better to use display a message in the dialog box rather than the pop up, can refer to how the confirmation message is displayed in delete command

Comment (yuqiannemo) [reply src/main/java/seedu/address/ui/PersonCard.java:275]: This one will be solved in a separate issue so I‘lol merge this PR first

**Review by yuqiannemo — APPROVED** [review]
